import type { VocabularyWord, WordCategory } from "./types";

/**
 * Mock vocabulary database for ages 4-12.
 * Sentences intentionally use only words a young child already hears daily.
 */

const SEED_TIME = new Date(0).toISOString(); // "due immediately" sentinel

function word(
  w: Omit<VocabularyWord, "imageUrl" | "nextReviewTime">,
): VocabularyWord {
  return {
    ...w,
    imageUrl: `/illustrations/${w.id}.svg`,
    nextReviewTime: SEED_TIME,
  };
}

export const VOCABULARY: VocabularyWord[] = [
  // ── Animals ────────────────────────────────────────────────
  word({
    id: "cat",
    word: "cat",
    phonetic: "/kæt/",
    translation: "猫",
    sentence_en: "The cat is soft.",
    sentence_zh: "小猫软软的。",
    category: "animals",
    tier: "beginner",
    emoji: "🐱",
  }),
  word({
    id: "dog",
    word: "dog",
    phonetic: "/dɒɡ/",
    translation: "狗",
    sentence_en: "The dog can run.",
    sentence_zh: "小狗会跑。",
    category: "animals",
    tier: "beginner",
    emoji: "🐶",
  }),
  word({
    id: "fish",
    word: "fish",
    phonetic: "/fɪʃ/",
    translation: "鱼",
    sentence_en: "The fish can swim.",
    sentence_zh: "小鱼会游泳。",
    category: "animals",
    tier: "beginner",
    emoji: "🐟",
  }),
  word({
    id: "bird",
    word: "bird",
    phonetic: "/bɜːd/",
    translation: "鸟",
    sentence_en: "The bird can sing.",
    sentence_zh: "小鸟会唱歌。",
    category: "animals",
    tier: "beginner",
    emoji: "🐦",
  }),
  word({
    id: "rabbit",
    word: "rabbit",
    phonetic: "/ˈræb.ɪt/",
    translation: "兔子",
    sentence_en: "The rabbit can jump.",
    sentence_zh: "小兔子会跳。",
    category: "animals",
    tier: "intermediate",
    emoji: "🐰",
  }),
  word({
    id: "panda",
    word: "panda",
    phonetic: "/ˈpæn.də/",
    translation: "熊猫",
    sentence_en: "The panda is black and white.",
    sentence_zh: "熊猫是黑白色的。",
    category: "animals",
    tier: "intermediate",
    emoji: "🐼",
  }),

  // ── Food ───────────────────────────────────────────────────
  word({
    id: "apple",
    word: "apple",
    phonetic: "/ˈæp.əl/",
    translation: "苹果",
    sentence_en: "I see a red apple.",
    sentence_zh: "我看见一个红苹果。",
    category: "food",
    tier: "beginner",
    emoji: "🍎",
  }),
  word({
    id: "banana",
    word: "banana",
    phonetic: "/bəˈnɑː.nə/",
    translation: "香蕉",
    sentence_en: "The banana is yellow.",
    sentence_zh: "香蕉是黄色的。",
    category: "food",
    tier: "beginner",
    emoji: "🍌",
  }),
  word({
    id: "milk",
    word: "milk",
    phonetic: "/mɪlk/",
    translation: "牛奶",
    sentence_en: "I drink milk.",
    sentence_zh: "我喝牛奶。",
    category: "food",
    tier: "beginner",
    emoji: "🥛",
  }),
  word({
    id: "egg",
    word: "egg",
    phonetic: "/eɡ/",
    translation: "鸡蛋",
    sentence_en: "I eat an egg.",
    sentence_zh: "我吃一个鸡蛋。",
    category: "food",
    tier: "beginner",
    emoji: "🥚",
  }),
  word({
    id: "bread",
    word: "bread",
    phonetic: "/bred/",
    translation: "面包",
    sentence_en: "The bread is warm.",
    sentence_zh: "面包暖暖的。",
    category: "food",
    tier: "intermediate",
    emoji: "🍞",
  }),
  word({
    id: "cake",
    word: "cake",
    phonetic: "/keɪk/",
    translation: "蛋糕",
    sentence_en: "The cake is sweet.",
    sentence_zh: "蛋糕甜甜的。",
    category: "food",
    tier: "intermediate",
    emoji: "🍰",
  }),

  // ── Colors ─────────────────────────────────────────────────
  word({
    id: "red",
    word: "red",
    phonetic: "/red/",
    translation: "红色",
    sentence_en: "The ball is red.",
    sentence_zh: "球是红色的。",
    category: "colors",
    tier: "beginner",
    emoji: "🔴",
  }),
  word({
    id: "blue",
    word: "blue",
    phonetic: "/bluː/",
    translation: "蓝色",
    sentence_en: "The sky is blue.",
    sentence_zh: "天空是蓝色的。",
    category: "colors",
    tier: "beginner",
    emoji: "🔵",
  }),
  word({
    id: "yellow",
    word: "yellow",
    phonetic: "/ˈjel.əʊ/",
    translation: "黄色",
    sentence_en: "The duck is yellow.",
    sentence_zh: "小鸭子是黄色的。",
    category: "colors",
    tier: "beginner",
    emoji: "💛",
  }),
  word({
    id: "green",
    word: "green",
    phonetic: "/ɡriːn/",
    translation: "绿色",
    sentence_en: "The leaf is green.",
    sentence_zh: "叶子是绿色的。",
    category: "colors",
    tier: "beginner",
    emoji: "🟢",
  }),
  word({
    id: "pink",
    word: "pink",
    phonetic: "/pɪŋk/",
    translation: "粉色",
    sentence_en: "The pig is pink.",
    sentence_zh: "小猪是粉色的。",
    category: "colors",
    tier: "intermediate",
    emoji: "🌸",
  }),
  word({
    id: "purple",
    word: "purple",
    phonetic: "/ˈpɜː.pəl/",
    translation: "紫色",
    sentence_en: "I like purple grapes.",
    sentence_zh: "我喜欢紫色的葡萄。",
    category: "colors",
    tier: "intermediate",
    emoji: "🍇",
  }),

  // ── Nature ─────────────────────────────────────────────────
  word({
    id: "sun",
    word: "sun",
    phonetic: "/sʌn/",
    translation: "太阳",
    sentence_en: "The sun is big.",
    sentence_zh: "太阳很大。",
    category: "nature",
    tier: "beginner",
    emoji: "☀️",
  }),
  word({
    id: "moon",
    word: "moon",
    phonetic: "/muːn/",
    translation: "月亮",
    sentence_en: "I see the moon.",
    sentence_zh: "我看见月亮。",
    category: "nature",
    tier: "beginner",
    emoji: "🌙",
  }),
  word({
    id: "star",
    word: "star",
    phonetic: "/stɑːr/",
    translation: "星星",
    sentence_en: "The star is bright.",
    sentence_zh: "星星亮亮的。",
    category: "nature",
    tier: "beginner",
    emoji: "⭐",
  }),
  word({
    id: "tree",
    word: "tree",
    phonetic: "/triː/",
    translation: "树",
    sentence_en: "The tree is tall.",
    sentence_zh: "树很高。",
    category: "nature",
    tier: "beginner",
    emoji: "🌳",
  }),
  word({
    id: "rain",
    word: "rain",
    phonetic: "/reɪn/",
    translation: "雨",
    sentence_en: "I hear the rain.",
    sentence_zh: "我听见下雨啦。",
    category: "nature",
    tier: "intermediate",
    emoji: "🌧️",
  }),
  word({
    id: "flower",
    word: "flower",
    phonetic: "/ˈflaʊ.ər/",
    translation: "花",
    sentence_en: "The flower is pretty.",
    sentence_zh: "花真漂亮。",
    category: "nature",
    tier: "intermediate",
    emoji: "🌷",
  }),
];

export const WORD_BY_ID: Record<string, VocabularyWord> = Object.fromEntries(
  VOCABULARY.map((w) => [w.id, w]),
);

export const CATEGORY_META: Record<
  WordCategory,
  { label: string; labelZh: string; emoji: string; gradient: string }
> = {
  animals: {
    label: "Animal Friends",
    labelZh: "动物朋友",
    emoji: "🦁",
    gradient: "from-orange-200 to-amber-100",
  },
  food: {
    label: "Yummy Food",
    labelZh: "美味食物",
    emoji: "🍓",
    gradient: "from-rose-200 to-pink-100",
  },
  colors: {
    label: "Rainbow Colors",
    labelZh: "彩虹颜色",
    emoji: "🌈",
    gradient: "from-violet-200 to-fuchsia-100",
  },
  nature: {
    label: "Big Nature",
    labelZh: "大自然",
    emoji: "🌻",
    gradient: "from-emerald-200 to-teal-100",
  },
};
